version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    command: rails s

volumes:
  pg-data: